### ISSUE TITLE
NodeProcess.cs might dead lock

### ISSUE THREAD

**Issue by marcwittke** [Wndrr/Mjml-CSharp#2]
Since you are redirecting standard out and standard error, the `process.Start()` followed by `process.WaitForExit()` might result in deadlocks. See this [answer on Stackoverflow](https://stackoverflow.com/a/7608823/164162).

**Comment by Wndrr** [comment]
I have taken note of your comment and will look into it ASAP. Thank you for letting me know :-)

**Comment by Wndrr** [comment]
I updated the code using the SO sample as a basis. NodeJs should no longer deadlock @marcwittke :-)
