### ISSUE TITLE
Mjml.PathRepository.NodePath is not used when installing mjml dependency

### ISSUE THREAD

**Issue by Dreamersoul** [Wndrr/Mjml-CSharp#4]
I have looked at the code and when the node process is initialized it assumes that the node.exe file is in the program folder

**Comment by Wndrr** [comment]
Sorry for not answering earlier ... I kind of forgot about this project ... until I needed it again (today).
I'll look into it in the coming days and let you know when it's fixed :-)

**Comment by Wndrr** [comment]
Now the `NodeProcess` class uses the `Mjml.PathRepository.NodePath` static property as the source for the path to node.exe as expected.
